FROM node:20.12.1-bookworm

WORKDIR /app

COPY --chown=node:node package*.json ./
RUN npm ci

COPY --chown=node:node .husky ./.husky
COPY --chown=node:node prisma ./prisma
COPY --chown=node:node tsconfig.json ./

RUN npm run prisma:gen

USER node

CMD ["npm", "run", "dev"]   