version: '3'

services:
  redis:
    container_name: redis
    image: redis/redis-stack:7.2.0-v10

    restart: unless-stopped
    ports:
      - 6379:6379
      - 8002:8001
    volumes:
      - redisdata:/data
    networks:
      - educonnect

volumes:
  redisdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./redis-data

networks:
  educonnect:
    name: educonnect
