version: '3'
services:
    db:
        image: postgres:16.0-alpine3.18
        container_name: educonnectDB
        restart: unless-stopped
        volumes:
            - ./db-init/scripts:/docker-entrypoint-initdb.d/:ro
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5435:5432'
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: password
            POSTGRES_DB: educonnect
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U dev -d educonnect']
            interval: 5s
            timeout: 5s
            retries: 3
    
    mongo:
        container_name: mongodb
        image: mongo:latest
        restart: unless-stopped
        volumes:
            - mgdata:/data/db
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: dev
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: educonnect
volumes:
    pgdata:

    mgdata:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./mg-data