version: '3'

services:
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - 6379:6379
      - 8002:8001
    volumes:
      - redisdata:/data

volumes:
  redisdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./redis-data

