CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE "user_role" AS ENUM ('admin', 'teacher', 'student', 'parent', 'user');

CREATE TYPE "user_sex" AS ENUM ('male', 'female', 'other');

CREATE TYPE "interact_type" AS ENUM ('like', 'love', 'haha', 'wow', 'sad', 'angry');

CREATE TYPE "member_role" AS ENUM ('admin', 'user');

CREATE TYPE "member_status" AS ENUM ('block', 'active', 'pending');

CREATE TABLE "user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "address" varchar,
    "name" varchar,
    "avatar" varchar,
    "background" varchar,
    "role" "user_role" NOT NULL,
    "phone" varchar,
    "birthday" TIMESTAMP,
    "email" varchar,
    "ssn" varchar UNIQUE,
    "sex" "user_sex",
    "user_uuid" uuid DEFAULT uuid_generate_v4 () NOT NULL,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL
);

CREATE TABLE "account" (
    "id" int PRIMARY KEY,
    "username" varchar UNIQUE,
    "password" varchar,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL
);

CREATE TABLE "follow" (
    "follower_id" int,
    "followed_id" int,
    "follow_times" int DEFAULT 1 NOT NULL,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL,
    PRIMARY KEY ("followed_id", "follower_id", "follow_times")
);

CREATE TABLE "notification" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" int NOT NULL,
    "message" varchar,
    "is_read" boolean DEFAULT False NOT NULL,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL
);

CREATE TABLE "post" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR DEFAULT '' NOT NULL,
    "content" varchar,
    "post_uuid" uuid DEFAULT uuid_generate_v4 () NOT NULL,
    "user_id" int NOT NULL,
    "parent_post_id" int,
    "group_id" int,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL
);

CREATE TABLE "interact" (
    "user_id" int,
    "post_id" int,
    "type" "interact_type",
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL,
    PRIMARY KEY ("user_id", "post_id")
);

CREATE TABLE "group" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "avatar" varchar,
    "background" varchar,
    "title" varchar,
    "meta_title" varchar,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL,
    "group_uuid" uuid DEFAULT uuid_generate_v4 () NOT NULL
);

CREATE TABLE "member" (
    "user_id" int,
    "group_id" int,
    "role" "member_role",
    "status" "member_status",
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL,
    PRIMARY KEY ("user_id", "group_id")
);

CREATE TABLE "admin" (
    "id" int PRIMARY KEY,
    "school_id" int,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL
);

CREATE TABLE "student" (
    "id" int PRIMARY KEY,
    "parent_id" int,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL
);

CREATE TABLE "parent" (
    "id" int PRIMARY KEY,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL
);

CREATE TABLE "teacher" (
    "id" int PRIMARY KEY,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL
);

CREATE TABLE "school" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "address" varchar,
    "name" varchar,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL
);

CREATE TABLE "classroom" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL,
    "school_id" int
);

CREATE TABLE "learn" (
    "class_id" int,
    "subject_id" int,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL,
    PRIMARY KEY ("class_id", "subject_id")
);

CREATE TABLE "document" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar,
    "url" varchar,
    "subject_id" int,
    "teacher_id" int,
    "document_uuid" uuid DEFAULT uuid_generate_v4 () NOT NULL,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL
);

CREATE TABLE "transcript" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "fifteen_minutes_score" FLOAT,
    "midterm_score" FLOAT,
    "final_score" FLOAT,
    "student_id" int,
    "subject_id" int,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL
);

CREATE TABLE "subject" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL
);

CREATE TABLE "teaching" (
    "subject_id" int,
    "teacher_id" int,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL,
    PRIMARY KEY ("subject_id", "teacher_id")
);

CREATE TABLE "of" (
    "student_id" int,
    "class_id" int,
    "create_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "update_at" TIMESTAMP DEFAULT (now ()) NOT NULL,
    "deleted" boolean DEFAULT False NOT NULL,
    PRIMARY KEY ("student_id", "class_id")
);

ALTER TABLE
    "account"
ADD
    FOREIGN KEY ("id") REFERENCES "user" ("id");

ALTER TABLE
    "follow"
ADD
    FOREIGN KEY ("followed_id") REFERENCES "user" ("id");

ALTER TABLE
    "follow"
ADD
    FOREIGN KEY ("follower_id") REFERENCES "user" ("id");

ALTER TABLE
    "notification"
ADD
    FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE
    "post"
ADD
    FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE
    "post"
ADD
    FOREIGN KEY ("parent_post_id") REFERENCES "post" ("id");

ALTER TABLE
    "post"
ADD
    FOREIGN KEY ("group_id") REFERENCES "group" ("id");

ALTER TABLE
    "interact"
ADD
    FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE
    "interact"
ADD
    FOREIGN KEY ("post_id") REFERENCES "post" ("id");

ALTER TABLE
    "member"
ADD
    FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE
    "member"
ADD
    FOREIGN KEY ("group_id") REFERENCES "group" ("id");

ALTER TABLE
    "admin"
ADD
    FOREIGN KEY ("id") REFERENCES "user" ("id");

ALTER TABLE
    "admin"
ADD
    FOREIGN KEY ("school_id") REFERENCES "school" ("id");

ALTER TABLE
    "student"
ADD
    FOREIGN KEY ("id") REFERENCES "user" ("id");

ALTER TABLE
    "student"
ADD
    FOREIGN KEY ("parent_id") REFERENCES "parent" ("id");

ALTER TABLE
    "parent"
ADD
    FOREIGN KEY ("id") REFERENCES "user" ("id");

ALTER TABLE
    "teacher"
ADD
    FOREIGN KEY ("id") REFERENCES "user" ("id");

ALTER TABLE
    "classroom"
ADD
    FOREIGN KEY ("school_id") REFERENCES "school" ("id");

ALTER TABLE
    "learn"
ADD
    FOREIGN KEY ("class_id") REFERENCES "classroom" ("id");

ALTER TABLE
    "learn"
ADD
    FOREIGN KEY ("subject_id") REFERENCES "subject" ("id");

ALTER TABLE
    "document"
ADD
    FOREIGN KEY ("subject_id") REFERENCES "subject" ("id");

ALTER TABLE
    "document"
ADD
    FOREIGN KEY ("teacher_id") REFERENCES "teacher" ("id");

ALTER TABLE
    "transcript"
ADD
    FOREIGN KEY ("student_id") REFERENCES "student" ("id");

ALTER TABLE
    "transcript"
ADD
    FOREIGN KEY ("subject_id") REFERENCES "subject" ("id");

ALTER TABLE
    "teaching"
ADD
    FOREIGN KEY ("subject_id") REFERENCES "subject" ("id");

ALTER TABLE
    "teaching"
ADD
    FOREIGN KEY ("teacher_id") REFERENCES "teacher" ("id");

ALTER TABLE
    "of"
ADD
    FOREIGN KEY ("student_id") REFERENCES "student" ("id");

ALTER TABLE
    "of"
ADD
    FOREIGN KEY ("class_id") REFERENCES "classroom" ("id");